language: php
php:
  - "5.4"
  - "5.3"
install:
  - composer self-update
  - composer install
  - npm install -g grunt-cli
  - npm install
script:
  - ./tests/run
  - npm test
notifications:
  irc:
    channels:
      - "chat.freenode.net##krinkle"
